#Provide list of your samples 
SAMPLE:
 - A
# - NA12878
# - NA24385
# - NA24149
# - NA24143

#Parameters for rule CUTADAPT_Trim1 and CUTADAPT_Trim2

adapter1_config: CTGTCTCTTATACACATCT
adapter2_config: CTGTCTCTTATACACATCT
q1_config: 20
q2_config: 20
cutadapt_threads_config: 6

#parameters for rule BWA_Mapping and SAMTOOLS_Sort
bwa_threads_config: 6
samtools_threads_config: 6

#parameters for rule GATK_VariantFiltration_Germline
gnomAD_Filter_config: 1
QD_Filter_config: 2.0
FS_Filter_config: 60.0
MQ_Filter_config: 40.0
MQRankSum_Filter_config: -12.5
ReadPosRankSum_Filter_config: -8.0
SOR_Filter_config: 3.0

#GATK JAVA memory
GATK_JAVA_config: -Xmx8g -Xmx4g

# Files for hg19 version of human reference genome
Ref_config: hg19
Reference: genome.fa
dbSNP_Database: dbSNP_hg19_sorted.vcf
TARGET_config: Target.bed
DataSource_config: dataSourcesFolder/
CutGermline_config: 332

