#Provide list of your samples 
SAMPLE:
 - A
# - NA12878
# - NA24385
# - NA24149
# - NA24143

#Parameters for rule CUTADAPT_Trim1 and CUTADAPT_Trim2

adapter1_config: CTGTCTCTTATACACATCT
adapter2_config: CTGTCTCTTATACACATCT
q1_config: 20
q2_config: 20
cutadapt_threads_config: 6

#parameters for rule BWA_Mapping and SAMTOOLS_Sort
bwa_threads_config: 6
samtools_threads_config: 6

#parameters for rule GATK_VariantFiltration_Somatic and GATK_VariantFiltration_Germline
gnomAD_Filter_config: 1
QD_Filter_config: 2.0
FS_Filter_config: 60.0
MQ_Filter_config: 40.0
MQRankSum_Filter_config: -12.5
ReadPosRankSum_Filter_config: -8.0
SOR_Filter_config: 3.0

#GATK JAVA memory
GATK_JAVA_config: -Xmx30g -Xmx20g

#parameters for rule GATK_BaseRecalibrator, GATK_BQSR, GATK_HaplotypeCaller and GATK_Mutect2

# Files for hg19 version of human reference genome
Ref_config: hg19
Reference: UCSCWholeGenomeFastaHG19/genome.fa
dbSNP_Database: dbSNP_20180423_hg19.vcf
MILLS_Database: Mills_and_1000G_gold_standard.indels.hg19.sites.vcf
dbSNPIndels_Database: 1000G_phase1.indels.hg19.sites.vcf
GNOMAD_Database: GNOMAD_hg19.vcf
TARGET_config: Target_hg19.bed
DataSource_config: dataSourcesFolderHG19/
CutGermline_config: 60
CutSomatic_config: 72

## Files for hg38 version of human reference genome
# Ref_config: hg38
# Reference: UCSCWholeGenomeFastaHG38/hg38.fa
# dbSNP_Database: dbSNP_20180418_hg38.vcf
# MILLS_Database: Mills_and_1000G_gold_standard.indels.hg38.vcf
# dbSNPIndels_Database: Homo_sapiens_hg38.known_indels.vcf
# GNOMAD_Database: GNOMAD_somatic-hg38_af-only.hg38.vcf
# TARGET_config: Target_hg38.bed
# DataSource_config: dataSourcesFolderHG38/
# CutGermline_config: 630
# CutSomatic_config: 642